services:
  db:
    image: postgres:latest
    container_name: springboot_postgres_db
    environment:
      POSTGRES_DB: order_book_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge

volumes:
  postgres_data:
